log-path = "./logs"
cache-mode = 2
[server]
    Address          = ":80"
    ServerRoot       = "public"
    LogPath          = "./logs"
    AccessLogEnabled = false
    ErrorLogEnabled  = true
    PProfEnabled     = true

# title设置
[setting]
    title = "配置管理中心"

# WebServer管理
[admin]
    user = "admin"
    pass = "123456"

# 数据库配置
[database]
    link = "mysql:root:123456@tcp(127.0.0.1:3306)/gcs"

# Redis数据库配置
[redis]
    default = "127.0.0.1:16379,0,soccer"
    cache   = "127.0.0.1:16379,1,soccer?idleTimeout=600"
