log-path = "./logs"
[server]
    Address          = ":80"
    ServerRoot       = "public"
    LogPath          = "./logs"
    AccessLogEnabled = false
    ErrorLogEnabled  = true
    PProfEnabled     = true

# title设置
[setting]
    title = "配置管理中心"

# WebServer管理
[admin]
    user = "admin"
    pass = "123"

# 数据库配置
[database]
    link = "mysql:root:A123456@tcp(127.0.0.1:33306)/gcs"