log-path = "./logs"
cache-mode = 2
[server]
    Address          = ":80"
    ServerRoot       = "public"
    LogPath          = "./logs"
    AccessLogEnabled = false
    ErrorLogEnabled  = true
    PProfEnabled     = true

# title设置
[setting]
    title = "配置管理中心"

# WebServer管理
[admin]
    user = "fulltimelink"
    pass = "nn5211314"

# 数据库配置
[database]
    link = "mysql:zhaijilei:ruyu2AXu2a@tcp(10.1.3.23:3308)/gcs"

# Redis数据库配置
[redis]
    default = "redis-hudong-master.general.svc.cluster.local:16379,3,b840fc02d524045429941cc15f59e41c89b7be6c"
    cache   = "redis-hudong-master.general.svc.cluster.local:16379,4,b840fc02d524045429941cc15f59e41c89b7be6c?idleTimeout=600"